---
- name: Setup Development Environment
  hosts: all

  roles:
    - sicruse.ansible_role_macdocker

  vars_files:
    - vars/vars.yml

  tasks:

    - name: Create filesystem mount point
      become: true
      file:
        path: '{{ nas_path }}'
        state: directory
        owner: root
        group: wheel
        mode: 0775

    - name: Writing auto_nas
      become: yes
      template: >
        src=templates/etc/auto_nas.j2
        dest=/etc/auto_nas
        mode=0644

    - name: Add auto_nas entry to auto_master
      become: yes
      blockinfile:
        dest: /etc/auto_master
        create: True
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          {{ nas_path }}        auto_nas

    - name: Mount NAS filesystem
      become: true
      command: automount -vc

    - name: Create media services docker directory
      become: true
      become_user: '{{ ansible_user_id }}'
      file:
        path: ~/media
        state: directory
        mode: 0775

    - name: Writing media services docker configuration
      become: yes
      become_user: '{{ ansible_user_id }}'
      template: >
        src=templates/media/docker-compose.yml.j2
        dest=~/media/docker-compose.yml
        mode=0755

    - name: Writing nginx reverse proxy configuration
      become: yes
      become_user: '{{ ansible_user_id }}'
      template: >
        src=templates/media/nginx.conf.j2
        dest=~/media/nginx.conf
        mode=0755

    - name: Create nginx logs directory
      become: true
      become_user: '{{ ansible_user_id }}'
      file:
        path: ~/media/logs
        state: directory
        mode: 0775

    - name: Create plex transcode directory
      become: true
      become_user: '{{ ansible_user_id }}'
      file:
        path: ~/media/transcode
        state: directory
        mode: 0775
